"""
Builder script for Full_Code_SuperKart_Model_Deployment_Notebook.ipynb.

Assembles the notebook cell by cell from the original template structure.
This script is a development tool used to author and regenerate the
notebook. It is not part of the graded deliverable itself.

Usage:
    .venv\\Scripts\\python.exe build_notebook.py
"""
import os

import nbformat as nbf

# Marker prepended to cells that call the live backend URL. These cells are
# skipped by execute_notebook.py since no live Codespace is running at
# authoring time. The exact text also functions as a lookup key there.
SKIP = (
    "# This cell calls the live Codespace backend URL and is skipped when this\n"
    "# notebook is executed locally, since no Codespace is running at authoring\n"
    "# time. The same request/response logic was already exercised end to end\n"
    "# in the Local Smoke Test section above. Run it yourself once model_root_url\n"
    "# below points at a real deployment.\n"
)

nb = nbf.v4.new_notebook()
C = []


def md(src):
    C.append(nbf.v4.new_markdown_cell(src))


def code(src):
    C.append(nbf.v4.new_code_cell(src))


# =====================================================================
# 0-6: Problem statement, business context, objective, data dictionary
#      (verbatim, as given in the original template)
# =====================================================================
md("# **Problem Statement**")
md("## Business Context")
md(
    "A sales forecast is a prediction of future sales revenue based on historical data, industry trends, and the status of the current sales pipeline. Businesses use the sales forecast to estimate weekly, monthly, quarterly, and annual sales totals. A company needs to make an accurate sales forecast as it adds value across an organization and helps the different verticals to chalk out their future course of action.\n\n"
    "Forecasting helps an organization plan its sales operations by region and provides valuable insights to the supply chain team regarding the procurement of goods and materials. An accurate sales forecast process has many benefits which include improved decision-making about the future and reduction of sales pipeline and forecast risks. Moreover, it helps to reduce the time spent in planning territory coverage and establish benchmarks that can be used to assess trends in the future."
)
md("## Objective")
md(
    "SuperKart is a retail chain operating supermarkets and food marts across various tier cities, offering a wide range of products. To optimize its inventory management and make informed decisions around regional sales strategies, SuperKart wants to accurately forecast the sales revenue of its outlets for the upcoming quarter.\n\n"
    "To operationalize these insights at scale, the company has partnered with a data science firm, not just to build a predictive model based on historical sales data, but to develop and deploy a robust forecasting solution that can be integrated into SuperKart's decision-making systems and used across its network of stores."
)
md("## Data Description")
md(
    "The data contains the different attributes of the various products and stores.The detailed data dictionary is given below.\n\n"
    "- **Product_Id** - unique identifier of each product, each identifier having two letters at the beginning followed by a number.\n"
    "- **Product_Weight** - weight of each product\n"
    "- **Product_Sugar_Content** - sugar content of each product like low sugar, regular and no sugar\n"
    "- **Product_Allocated_Area** - ratio of the allocated display area of each product to the total display area of all the products in a store\n"
    "- **Product_Type** - broad category for each product like meat, snack foods, hard drinks, dairy, canned, soft drinks, health and hygiene, baking goods, bread, breakfast, frozen foods, fruits and vegetables, household, seafood, starchy foods, others\n"
    "- **Product_MRP** - maximum retail price of each product\n"
    "- **Store_Id** - unique identifier of each store\n"
    "- **Store_Establishment_Year** - year in which the store was established\n"
    "- **Store_Size** - size of the store depending on sq. feet like high, medium and low\n"
    "- **Store_Location_City_Type** - type of city in which the store is located like Tier 1, Tier 2 and Tier 3. Tier 1 consists of cities where the standard of living is comparatively higher than its Tier 2 and Tier 3 counterparts.\n"
    "- **Store_Type** - type of store depending on the products that are being sold there like Departmental Store, Supermarket Type 1, Supermarket Type 2 and Food Mart\n"
    "- **Product_Store_Sales_Total** - total revenue generated by the sale of that particular product in that particular store\n"
)

# =====================================================================
# 7-10: Installing / importing libraries (verbatim, plus the extra
# ensemble regressors we now need for all 6 model families)
# =====================================================================
md("# **Installing and Importing the necessary libraries**")
code(
    "#Installing the libraries with the specified versions\n"
    "!pip install numpy==2.0.2 pandas==2.2.2 scikit-learn==1.6.1 matplotlib==3.10.0 seaborn==0.13.2 joblib==1.4.2 xgboost==2.1.4 requests==2.32.4 huggingface_hub==0.34.0 -q"
)
md(
    "**Note:**\n\n"
    "- After running the above cell, kindly restart the notebook kernel (for Jupyter Notebook) or runtime (for Google Colab) and run all cells sequentially from the next cell.\n\n"
    "- On executing the above line of code, you might see a warning regarding package dependencies. This error message can be ignored as the above code ensures that all necessary libraries and their dependencies are maintained to successfully execute the code in this notebook."
)
code(
    'import warnings\n'
    'warnings.filterwarnings("ignore")\n'
    '\n'
    '# Libraries to help with reading and manipulating data\n'
    'import numpy as np\n'
    'import pandas as pd\n'
    '\n'
    '# For splitting the dataset\n'
    'from sklearn.model_selection import train_test_split\n'
    '\n'
    '# Libaries to help with data visualization\n'
    'import matplotlib.pyplot as plt\n'
    'import seaborn as sns\n'
    '\n'
    '# Removes the limit for the number of displayed columns\n'
    'pd.set_option("display.max_columns", None)\n'
    '# Sets the limit for the number of displayed rows\n'
    'pd.set_option("display.max_rows", 100)\n'
    '\n'
    '\n'
    '# Ensemble regressors covering all six model families we build below:\n'
    '# Decision Tree, Bagging, Random Forest, AdaBoost, Gradient Boosting, XGBoost\n'
    'from sklearn.tree import DecisionTreeRegressor\n'
    'from sklearn.ensemble import (\n'
    '    BaggingRegressor,\n'
    '    RandomForestRegressor,\n'
    '    AdaBoostRegressor,\n'
    '    GradientBoostingRegressor,\n'
    ')\n'
    'from xgboost import XGBRegressor\n'
    '\n'
    '# Libraries to get different metric scores\n'
    'from sklearn.metrics import (\n'
    '    confusion_matrix,\n'
    '    accuracy_score,\n'
    '    precision_score,\n'
    '    recall_score,\n'
    '    f1_score,\n'
    '    mean_squared_error,\n'
    '    mean_absolute_error,\n'
    '    r2_score,\n'
    '    mean_absolute_percentage_error\n'
    ')\n'
    '\n'
    '# To create the pipeline\n'
    'from sklearn.compose import make_column_transformer\n'
    'from sklearn.pipeline import make_pipeline,Pipeline\n'
    '\n'
    '# To tune different models and standardize\n'
    'from sklearn.model_selection import GridSearchCV\n'
    'from sklearn.preprocessing import StandardScaler,OneHotEncoder\n'
    '\n'
    '# To serialize the model\n'
    'import joblib\n'
    '\n'
    '# os related functionalities\n'
    'import os\n'
    '\n'
    '# API request\n'
    'import requests\n'
    '\n'
    '# for hugging face space authentication to upload files\n'
    'from huggingface_hub import login, HfApi'
)

# =====================================================================
# Loading the dataset
# =====================================================================
md("# **Loading the dataset**")
code(
    "# Each row is one product sold at one store, with product and store\n"
    "# attributes plus the total revenue that product generated at that store.\n"
    'data = pd.read_csv("SuperKart.csv")\n'
    "\n"
    "# Keep a copy so the raw file stays untouched if we need to re-check anything\n"
    "df = data.copy()\n"
    "\n"
    "df.head()"
)

# =====================================================================
# Data Overview
# =====================================================================
md("# **Data Overview**")

md("## Shape of the Data")
code('print(f"{df.shape[0]} rows, {df.shape[1]} columns.")')

md("## First and Last Rows")
code("df.head()")
code("df.tail()")

md("## Random Sample of Rows")
md(
    "Head and tail only show rows near the two ends of the file. A random sample gives a "
    "better read on what a typical row looks like across the full dataset, not just the "
    "beginning and end."
)
code("df.sample(n=5, random_state=1)")

md("## Data Types")
code("df.info()")
md(
    "5 numeric columns (`Product_Weight`, `Product_Allocated_Area`, `Product_MRP`, "
    "`Store_Establishment_Year`, `Product_Store_Sales_Total`) and 7 object columns. "
    "`Store_Establishment_Year` is stored as an integer but is really a calendar marker, "
    "not a magnitude, so we will convert it into a store age later."
)

md("## Missing Values")
code("df.isnull().sum()")
md("No missing values anywhere. No imputation needed.")

md("## Duplicate Rows")
code('print(f"Duplicate rows: {df.duplicated().sum()}")')
md("No duplicates.")

md("## Unique Values per Column")
code("df.nunique()")
md(
    "`Product_Id` is unique on every row (8,763 values), so it carries no information a model "
    "can generalize from directly. `Store_Id` only takes 4 values. `Product_Type` has 16 "
    "categories, which is a lot relative to having just 4 stores in the data."
)

md("## Statistical Summary")
code("df.describe().T")
code('df.describe(include="object").T')
md(
    "Numeric ranges look sensible: `Product_Weight` 4 to 22, `Product_MRP` 31 to 266, "
    "`Product_Store_Sales_Total` 33 to 8,000 with mean and median close together (3,464 vs "
    "3,452), so the target is not badly skewed. One thing stands out in the categorical "
    "summary: `Product_Sugar_Content` shows 4 unique values, but the data dictionary only "
    "documents 3 (Low Sugar, Regular, No Sugar). Worth a closer look."
)

md("## Fixing a Data Quality Issue")
code(
    'print("Before:", df["Product_Sugar_Content"].unique())\n'
    "\n"
    "# 'reg' is the same thing as 'Regular', just entered inconsistently somewhere\n"
    "# upstream. Folding it in so the encoder does not treat it as a separate category.\n"
    'df["Product_Sugar_Content"] = df["Product_Sugar_Content"].replace({"reg": "Regular"})\n'
    "\n"
    'print("After: ", df["Product_Sugar_Content"].unique())'
)

md(
    "### Summary\n"
    "- 8,763 rows, 12 columns, no missing values, no duplicates.\n"
    "- One data quality issue found and fixed: `'reg'` folded into `'Regular'` in `Product_Sugar_Content`.\n"
    "- `Product_Id` is a row-level identifier and `Store_Id` only has 4 values. Both need to be engineered rather than fed to the model as raw categories.\n"
    "- Numeric columns and the target have sane, non-negative ranges with nothing that looks like a data entry error.\n"
    "- `Product_Type` (16 categories) and `Store_Establishment_Year` (only 4 distinct values) are both good candidates for feature engineering, covered later."
)

# =====================================================================
# Exploratory Data Analysis (EDA)
# =====================================================================
md("# **Exploratory Data Analysis (EDA)**")
md("## Univariate Analysis")
md(
    "Two small helper functions keep the plots consistent across every numeric and "
    "categorical column: one for a boxplot plus histogram pair, one for a labeled "
    "count plot."
)
code(
    'def histogram_boxplot(data, feature, figsize=(12, 5), bins="auto"):\n'
    '    """\n'
    "    Boxplot on top, histogram with KDE below, sharing the x-axis.\n"
    "    Lets you see distribution shape and outliers together.\n"
    '    """\n'
    "    f2, (ax_box, ax_hist) = plt.subplots(\n"
    '        nrows=2, sharex=True, gridspec_kw={"height_ratios": (0.25, 0.75)}, figsize=figsize\n'
    "    )\n"
    '    sns.boxplot(data=data, x=feature, ax=ax_box, showmeans=True, color="violet")\n'
    '    sns.histplot(data=data, x=feature, kde=True, ax=ax_hist, bins=bins, color="skyblue")\n'
    '    ax_hist.axvline(data[feature].mean(), color="green", linestyle="--", label="Mean")\n'
    '    ax_hist.axvline(data[feature].median(), color="black", linestyle="-", label="Median")\n'
    "    ax_hist.legend()\n"
    '    plt.suptitle(f"Distribution of {feature}")\n'
    "    plt.tight_layout()\n"
    "    plt.show()\n"
    "\n"
    "\n"
    "def labeled_barplot(data, feature, figsize=(10, 5)):\n"
    '    """\n'
    "    Count plot for a categorical feature, ordered by frequency, with the\n"
    "    count for each bar printed above it.\n"
    '    """\n'
    "    total = len(data[feature])\n"
    "    n_unique = data[feature].nunique()\n"
    "    order = data[feature].value_counts().index\n"
    "    plt.figure(figsize=figsize)\n"
    '    ax = sns.countplot(data=data, x=feature, order=order, hue=feature, palette="viridis", legend=False)\n'
    "    for p in ax.patches:\n"
    '        ax.annotate(\n'
    '            f"{p.get_height():,.0f}",\n'
    "            (p.get_x() + p.get_width() / 2, p.get_height()),\n"
    '            ha="center", va="bottom", fontsize=10, xytext=(0, 3), textcoords="offset points",\n'
    "        )\n"
    '    plt.title(f"Distribution of {feature} ({n_unique} categories)")\n'
    '    plt.xticks(rotation=30, ha="right")\n'
    "    plt.tight_layout()\n"
    "    plt.show()"
)

md("### Product_Weight")
code('histogram_boxplot(df, "Product_Weight")')
md("Roughly symmetric between 4 and 22, mean and median almost on top of each other. A few mild outliers on both ends, nothing extreme.")

md("### Product_Allocated_Area")
code('histogram_boxplot(df, "Product_Allocated_Area")')
md("Right skewed. Most products take up a small share of shelf space, and a smaller group takes up noticeably more.")

md("### Product_MRP")
code('histogram_boxplot(df, "Product_MRP")')
md("Fairly symmetric across the full price range, no strong skew.")

md("### Product_Store_Sales_Total (target)")
code('histogram_boxplot(df, "Product_Store_Sales_Total")')
md("Mildly right skewed with a handful of high value outliers, but nothing severe. Mean and median are close.")

md("### Store_Establishment_Year")
code('labeled_barplot(df, "Store_Establishment_Year")')
md("Only 4 distinct years, one per store, as expected. The store established in 2009 alone accounts for over half the rows, so it clearly stocks a much wider product range than the others.")

md("### Product_Sugar_Content")
code('labeled_barplot(df, "Product_Sugar_Content")')
md("Low Sugar dominates (~56%), Regular is next (~27%), No Sugar (~17%) is mostly non-consumable products where sugar content does not really apply.")

md("### Product_Type")
code('labeled_barplot(df, "Product_Type", figsize=(14, 5))')
md("Fruits and Vegetables and Snack Foods are the most common categories, Seafood and Breakfast the least. Sixteen categories with this much imbalance is a good argument for a coarser grouping later.")

md("### Store_Size")
code('labeled_barplot(df, "Store_Size")')
md("Medium stores make up ~69% of rows, tracking back to the same large store noted above.")

md("### Store_Location_City_Type")
code('labeled_barplot(df, "Store_Location_City_Type")')
md("Tier 2 dominates (~71%), for the same reason.")

md("### Store_Type")
code('labeled_barplot(df, "Store_Type")')
md("Supermarket Type2 accounts for over half the rows.")

md(
    "### Summary\n"
    "- `Product_MRP` and `Product_Allocated_Area` are close to symmetric, `Product_Store_Sales_Total` is only mildly skewed.\n"
    "- Every store level column (`Store_Establishment_Year`, `Store_Size`, `Store_Location_City_Type`, `Store_Type`) shows the exact same proportions, which points to all four traceable back to the same 4 stores. Confirmed in the bivariate section below.\n"
    "- `Product_Type` at 16 categories with real imbalance is a candidate for a coarser grouping."
)

# ---------------------------------------------------------------
# Bivariate Analysis
# ---------------------------------------------------------------
md("## Bivariate Analysis")

md("### Correlation Among Numeric Features")
code(
    'plt.figure(figsize=(8, 6))\n'
    'sns.heatmap(df.corr(numeric_only=True), annot=True, fmt=".2f", cmap="coolwarm", vmin=-1, vmax=1)\n'
    'plt.title("Correlation Heatmap")\n'
    "plt.tight_layout()\n"
    "plt.show()"
)
md(
    "`Product_MRP` (~0.79) and `Product_Weight` (~0.74) correlate most strongly with the target. "
    "`Product_Allocated_Area` shows almost no linear relationship with sales. "
    "`Store_Establishment_Year` has a mild negative correlation, likely a store mix effect rather than a real aging effect."
)

md("### Product_MRP vs. Product_Store_Sales_Total")
code(
    'plt.figure(figsize=(8, 5))\n'
    'sns.scatterplot(data=df, x="Product_MRP", y="Product_Store_Sales_Total", alpha=0.4)\n'
    'plt.title("Product_MRP vs. Product_Store_Sales_Total")\n'
    "plt.tight_layout()\n"
    "plt.show()"
)
md("Clear positive relationship. Higher priced products generate more revenue, with more spread at the higher end.")

md("### Product_Weight vs. Product_Store_Sales_Total")
code(
    'plt.figure(figsize=(8, 5))\n'
    'sns.scatterplot(data=df, x="Product_Weight", y="Product_Store_Sales_Total", alpha=0.4)\n'
    'plt.title("Product_Weight vs. Product_Store_Sales_Total")\n'
    "plt.tight_layout()\n"
    "plt.show()"
)
md("Same pattern as MRP: heavier products tend to sell for more.")

md("### Sales by Store_Type")
code(
    'plt.figure(figsize=(8, 5))\n'
    'sns.boxplot(data=df, x="Store_Type", y="Product_Store_Sales_Total", hue="Store_Type", palette="Set2", legend=False)\n'
    'plt.title("Product_Store_Sales_Total by Store_Type")\n'
    "plt.xticks(rotation=15)\n"
    "plt.tight_layout()\n"
    "plt.show()"
)
md("Departmental Store has the highest median, Food Mart the lowest. Store format is clearly tied to sales potential.")

md("### Sales by Store_Size")
code(
    'plt.figure(figsize=(8, 5))\n'
    'sns.boxplot(data=df, x="Store_Size", y="Product_Store_Sales_Total", hue="Store_Size", order=["Small", "Medium", "High"], palette="Set2", legend=False)\n'
    'plt.title("Product_Store_Sales_Total by Store_Size")\n'
    "plt.tight_layout()\n"
    "plt.show()"
)
md("High and Medium sized stores sell noticeably more than Small stores.")

md("### Sales by Store_Location_City_Type")
code(
    'plt.figure(figsize=(8, 5))\n'
    'sns.boxplot(data=df, x="Store_Location_City_Type", y="Product_Store_Sales_Total", hue="Store_Location_City_Type", order=["Tier 1", "Tier 2", "Tier 3"], palette="Set2", legend=False)\n'
    'plt.title("Product_Store_Sales_Total by Store_Location_City_Type")\n'
    "plt.tight_layout()\n"
    "plt.show()"
)
md("Tier 1 has the highest median, Tier 3 the lowest, consistent with purchasing power differences across city tiers.")

md("### How the Store Attributes Relate to Each Other")
code('pd.crosstab(df["Store_Id"], [df["Store_Type"], df["Store_Size"], df["Store_Location_City_Type"]])')
md(
    "Each `Store_Id` maps to exactly one combination of `Store_Type`, `Store_Size`, and "
    "`Store_Location_City_Type`. With only 4 stores in the data, these columns are fully "
    "redundant with `Store_Id` itself. That means `Store_Id` adds nothing beyond what the "
    "three descriptive columns already capture, and being a raw identifier it would not "
    "generalize to a store opened after this dataset was collected. We drop `Store_Id` and "
    "keep the three descriptive attributes instead."
)

md("### Sales by Product_Type")
code(
    'plt.figure(figsize=(14, 5))\n'
    'order = df.groupby("Product_Type")["Product_Store_Sales_Total"].median().sort_values(ascending=False).index\n'
    'sns.boxplot(data=df, x="Product_Type", y="Product_Store_Sales_Total", order=order, hue="Product_Type", palette="Set3", legend=False)\n'
    'plt.title("Product_Store_Sales_Total by Product_Type")\n'
    "plt.xticks(rotation=30, ha=\"right\")\n"
    "plt.tight_layout()\n"
    "plt.show()"
)
md("Medians are fairly close across product types, with Starchy Foods and Seafood trending a bit higher. Price and weight still dominate over the product category itself.")

md("### Sales by Product_Sugar_Content")
code(
    'plt.figure(figsize=(8, 5))\n'
    'sns.boxplot(data=df, x="Product_Sugar_Content", y="Product_Store_Sales_Total", hue="Product_Sugar_Content", palette="Set2", legend=False)\n'
    'plt.title("Product_Store_Sales_Total by Product_Sugar_Content")\n'
    "plt.tight_layout()\n"
    "plt.show()"
)
md("Distributions look similar across categories. A minor effect at best, possibly useful in combination with other features.")

md(
    "### Key Insights from EDA\n"
    "1. `Product_MRP` and `Product_Weight` are the strongest numeric drivers of sales.\n"
    "2. Store format matters, but `Store_Type`, `Store_Size`, and `Store_Location_City_Type` are three views of the same 4 stores, not independent evidence.\n"
    "3. `Store_Id` and `Product_Id` are identifiers that do not generalize and need to be engineered rather than used directly.\n"
    "4. `Product_Type` has only a mild effect on sales by itself and can be grouped into broader buckets without losing much.\n"
    "5. The target is only mildly skewed with no outliers that look like errors.\n"
    "6. One data quality issue was found and fixed during the overview."
)

# =====================================================================
# Data Preprocessing
# =====================================================================
md("# **Data Preprocessing**")

md("## Feature Engineering")
md(
    "Three raw columns need transforming instead of being used as is:\n"
    "- `Product_Id` is unique per row, but its first two characters carry a real category (`FD` food, `DR` drinks, `NC` non-consumable).\n"
    "- `Store_Establishment_Year` is a calendar year. Store age in years is more directly useful for a forecasting model and stays meaningful as new data comes in.\n"
    "- `Product_Type` has 16 categories. Grouping them into Perishable vs. Non-Perishable captures a business-relevant distinction (shelf life, restocking frequency) while cutting down sparsity.\n\n"
    "`Store_Id` is dropped, since the bivariate analysis showed it is a 1:1, non-generalizable stand-in for `Store_Type`, `Store_Size`, and `Store_Location_City_Type`, which we keep instead."
)
code(
    "# Product_Id_char: broad product category from the first two characters of\n"
    "# Product_Id (FD food, DR drinks, NC non-consumable). Turns a per-row identifier\n"
    "# into a low-cardinality category that still applies to products not yet seen.\n"
    'df["Product_Id_char"] = df["Product_Id"].str[:2]\n'
    "\n"
    "# Store_Age_Years: store age relative to the reference year this dataset was\n"
    "# compiled (2025), computed once and reused everywhere downstream, including\n"
    "# the deployed API and the Streamlit frontend.\n"
    "CURRENT_YEAR = 2025\n"
    'df["Store_Age_Years"] = CURRENT_YEAR - df["Store_Establishment_Year"]\n'
    "\n"
    "# Product_Type_Category: groups the 16 Product_Type values into Perishables\n"
    "# and Non Perishables, a coarser split that still carries useful signal.\n"
    'PERISHABLE_TYPES = ["Dairy", "Meat", "Fruits and Vegetables", "Breads", "Breakfast", "Seafood"]\n'
    'df["Product_Type_Category"] = np.where(\n'
    '    df["Product_Type"].isin(PERISHABLE_TYPES), "Perishables", "Non Perishables"\n'
    ")\n"
    "\n"
    "# Drop columns now superseded by the engineered features, or that are\n"
    "# identifiers/redundant with other store attributes:\n"
    "#   Product_Id                 -> unique per row, no generalizable signal\n"
    "#   Product_Type                -> superseded by Product_Type_Category\n"
    "#   Store_Id                    -> redundant with Store_Size / Store_Type / City (see EDA)\n"
    "#   Store_Establishment_Year    -> superseded by Store_Age_Years\n"
    'df.drop(columns=["Product_Id", "Product_Type", "Store_Id", "Store_Establishment_Year"], inplace=True)\n'
    "\n"
    "df.head()"
)
code("df.tail()")
code("df.sample(n=5, random_state=1)")
code('df.info()')
md(
    "All three engineered features are derived purely from data already in the dataset, "
    "no external lookups involved. They cut cardinality (`Product_Type` 16 down to 2, "
    "`Product_Id` 8,763 unique values down to 3 categories) and replace a non-generalizable "
    "identifier and a fixed calendar year with features that will still make sense for future "
    "products and future quarters. No polynomial or interaction terms were added on top of this, "
    "since the tree-based models used below can learn non-linear interactions on their own."
)

md("## Outlier Detection and Treatment")
md("IQR method on the continuous numeric features, including the target.")
code(
    'num_cols = ["Product_Weight", "Product_Allocated_Area", "Product_MRP", "Store_Age_Years", "Product_Store_Sales_Total"]\n'
    "\n"
    "outlier_rows = []\n"
    "for col in num_cols:\n"
    "    q1, q3 = df[col].quantile([0.25, 0.75])\n"
    "    iqr = q3 - q1\n"
    "    lower, upper = q1 - 1.5 * iqr, q3 + 1.5 * iqr\n"
    "    n_out = df[(df[col] < lower) | (df[col] > upper)].shape[0]\n"
    "    outlier_rows.append([col, round(lower, 3), round(upper, 3), n_out, round(100 * n_out / len(df), 2)])\n"
    "\n"
    "outlier_summary = pd.DataFrame(\n"
    '    outlier_rows, columns=["Feature", "Lower Bound", "Upper Bound", "No. of Outliers", "% of Data"]\n'
    ")\n"
    "outlier_summary"
)
code(
    "fig, axes = plt.subplots(1, len(num_cols), figsize=(4 * len(num_cols), 5))\n"
    "for ax, col in zip(axes, num_cols):\n"
    '    sns.boxplot(y=df[col], ax=ax, color="#66c2a5")\n'
    "    ax.set_title(col)\n"
    'plt.suptitle("Boxplots of Continuous Features")\n'
    "plt.tight_layout()\n"
    "plt.show()"
)
md(
    "Flagged points are under 5% for every column, and they look like real business "
    "observations (premium products, high performing store-product combinations), not data "
    "entry mistakes. These are exactly the cases a sales forecast needs to get right, so removing "
    "them would work against the goal. All six models we build are tree-based ensembles, which "
    "split on rank order and are not sensitive to the absolute scale of extreme values. Outliers "
    "are documented here but left untreated."
)

md("## Train, Validation, and Test Split")
md(
    "A single train-test split is not enough here, because model selection itself needs data "
    "that the final reported number has never touched. We split the data three ways instead:\n"
    "- **Train (60%)**: fits every model, and is what `GridSearchCV` folds internally when tuning.\n"
    "- **Validation (20%)**: used below to compare all baseline and tuned candidates against each "
    "other and pick the final model. This is a separate concern from the cross-validation folds "
    "`GridSearchCV` uses, which only ever see the training split. Validation compares different "
    "model families and baseline vs. tuned, cross-validation tunes hyperparameters within a "
    "single model family.\n"
    "- **Test (20%)**: held out completely until the final model has already been chosen. It "
    "plays no part in fitting any model or in picking the winner. Its only job is to report an "
    "honest, unbiased estimate of how the chosen model performs on data it never influenced."
)
code(
    "# Separate target from predictors\n"
    'X = df.drop(columns=["Product_Store_Sales_Total"])\n'
    'y = df["Product_Store_Sales_Total"]\n'
    "\n"
    "# First carve out the 60% training split, then split the remaining 40%\n"
    "# evenly into validation and test (20% each of the full dataset)\n"
    "X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.4, random_state=1)\n"
    "X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=1)\n"
    "\n"
    'print("Train:     ", X_train.shape)\n'
    'print("Validation:", X_val.shape)\n'
    'print("Test:      ", X_test.shape)'
)

md("## Preprocessing Pipeline")
md(
    "A `ColumnTransformer` handles both feature types:\n"
    "- Categorical columns get one-hot encoded with `handle_unknown=\"ignore\"`, so a category not seen during training does not break inference in production.\n"
    "- Numeric columns get standardized. The tree models below do not strictly need this, but it keeps the pipeline reusable with scale-sensitive models later and costs nothing here.\n\n"
    "Wrapping preprocessing and model together in one `Pipeline` means the same transformation runs at training time, at evaluation time, and later inside the Flask API, with no risk of the three getting out of sync."
)
code(
    'num_features = ["Product_Weight", "Product_Allocated_Area", "Product_MRP", "Store_Age_Years"]\n'
    'cat_features = [\n'
    '    "Product_Sugar_Content",\n'
    '    "Store_Size",\n'
    '    "Store_Location_City_Type",\n'
    '    "Store_Type",\n'
    '    "Product_Id_char",\n'
    '    "Product_Type_Category",\n'
    "]\n"
    "\n"
    "preprocessor = make_column_transformer(\n"
    "    (StandardScaler(), num_features),\n"
    '    (OneHotEncoder(handle_unknown="ignore"), cat_features),\n'
    '    remainder="drop",\n'
    ")\n"
    "preprocessor"
)

# =====================================================================
# Model Building
# =====================================================================
md("# **Model Building**")

md("## Metric of Choice")
md(
    "This is a regression problem, so classification metrics do not apply. We track several "
    "regression metrics, but use **RMSE** as the metric of choice for ranking models and driving "
    "hyperparameter tuning, for two reasons. First, it is in the same unit as the target "
    "(currency), so a business stakeholder can read it directly as an error in rupees. Second, "
    "the squared term penalizes large misses more than small ones, which fits a forecasting "
    "problem where a handful of badly wrong predictions can drive real stock-out or overstock cost.\n\n"
    "MAE, R-squared, Adjusted R-squared, and MAPE are reported alongside RMSE for a fuller picture, "
    "but RMSE is what decides model ranking and tuning."
)

md("## Model Evaluation Functions")
code(
    "# function to compute adjusted R-squared\n"
    "def adj_r2_score(predictors, targets, predictions):\n"
    "    r2 = r2_score(targets, predictions)\n"
    "    n = predictors.shape[0]\n"
    "    k = predictors.shape[1]\n"
    "    return 1 - ((1 - r2) * (n - 1) / (n - k - 1))\n"
    "\n"
    "\n"
    "# function to compute different metrics to check performance of a regression model\n"
    "def model_performance_regression(model, predictors, target):\n"
    '    """\n'
    "    Function to compute different metrics to check regression model performance\n"
    "\n"
    "    model: regressor\n"
    "    predictors: independent variables\n"
    "    target: dependent variable\n"
    '    """\n'
    "\n"
    "    # predicting using the independent variables\n"
    "    pred = model.predict(predictors)\n"
    "\n"
    "    r2 = r2_score(target, pred)  # to compute R-squared\n"
    "    adjr2 = adj_r2_score(predictors, target, pred)  # to compute adjusted R-squared\n"
    "    rmse = np.sqrt(mean_squared_error(target, pred))  # to compute RMSE\n"
    "    mae = mean_absolute_error(target, pred)  # to compute MAE\n"
    "    mape = mean_absolute_percentage_error(target, pred)  # to compute MAPE\n"
    "\n"
    "    # creating a dataframe of metrics\n"
    "    df_perf = pd.DataFrame(\n"
    "        {\n"
    '            "RMSE": rmse,\n'
    '            "MAE": mae,\n'
    '            "R-squared": r2,\n'
    '            "Adj. R-squared": adjr2,\n'
    '            "MAPE": mape,\n'
    "        },\n"
    "        index=[0],\n"
    "    )\n"
    "\n"
    "    return df_perf"
)

md(
    "The ML models to be built can be any two out of the following:\n"
    "1. Decision Tree\n"
    "2. Bagging\n"
    "3. Random Forest\n"
    "4. AdaBoost\n"
    "5. Gradient Boosting\n"
    "6. XGBoost"
)
md(
    "We build all six of the model families listed above rather than just two, to get a "
    "complete comparison across the tree-based ensemble family: **Decision Tree**, **Bagging**, "
    "**Random Forest**, **AdaBoost**, **Gradient Boosting**, and **XGBoost**. Each one is wrapped "
    "with the same `preprocessor` inside a single `Pipeline`, so every model is trained and "
    "evaluated through an identical preprocessing path.\n\n"
    "To avoid writing six nearly-identical blocks of code, model definitions and hyperparameter "
    "grids are kept in one dictionary and both the baseline fitting loop and the tuning loop "
    "further below iterate over it. Adding, removing, or re-tuning a model family only means "
    "editing this one place."
)
code(
    "# Estimator and hyperparameter grid for each of the six model families.\n"
    "# Grid sizes are kept modest so the full tuning pass finishes in a reasonable\n"
    "# time on this dataset (under 9,000 rows), while still covering the parameters\n"
    "# that matter most for controlling overfitting in each family.\n"
    "MODEL_CONFIGS = {\n"
    '    "Decision Tree": {\n'
    '        "estimator": DecisionTreeRegressor(random_state=1),\n'
    '        "param_grid": {\n'
    '            "model__max_depth": [4, 8, 12, None],\n'
    '            "model__min_samples_leaf": [1, 5, 10],\n'
    "        },\n"
    "    },\n"
    '    "Bagging": {\n'
    '        "estimator": BaggingRegressor(random_state=1),\n'
    '        "param_grid": {\n'
    '            "model__n_estimators": [50, 100],\n'
    '            "model__max_samples": [0.7, 1.0],\n'
    '            "model__max_features": [0.7, 1.0],\n'
    "        },\n"
    "    },\n"
    '    "Random Forest": {\n'
    '        "estimator": RandomForestRegressor(random_state=1),\n'
    '        "param_grid": {\n'
    '            "model__n_estimators": [100, 200],\n'
    '            "model__max_depth": [8, 12, None],\n'
    '            "model__min_samples_leaf": [1, 5, 10],\n'
    '            "model__max_features": ["sqrt", 1.0],\n'
    "        },\n"
    "    },\n"
    '    "AdaBoost": {\n'
    '        "estimator": AdaBoostRegressor(random_state=1),\n'
    '        "param_grid": {\n'
    '            "model__n_estimators": [50, 100, 200],\n'
    '            "model__learning_rate": [0.05, 0.1, 0.5],\n'
    "        },\n"
    "    },\n"
    '    "Gradient Boosting": {\n'
    '        "estimator": GradientBoostingRegressor(random_state=1),\n'
    '        "param_grid": {\n'
    '            "model__n_estimators": [100, 200],\n'
    '            "model__max_depth": [2, 3, 4],\n'
    '            "model__learning_rate": [0.05, 0.1],\n'
    '            "model__subsample": [0.8, 1.0],\n'
    "        },\n"
    "    },\n"
    '    "XGBoost": {\n'
    '        "estimator": XGBRegressor(random_state=1, eval_metric="rmse"),\n'
    '        "param_grid": {\n'
    '            "model__n_estimators": [150, 300],\n'
    '            "model__max_depth": [3, 5, 7],\n'
    '            "model__learning_rate": [0.03, 0.1],\n'
    '            "model__subsample": [0.8, 1.0],\n'
    '            "model__colsample_bytree": [0.8, 1.0],\n'
    "        },\n"
    "    },\n"
    "}\n"
    "\n"
    'print("Model families:", list(MODEL_CONFIGS.keys()))'
)

md("## Baseline Models")
md(
    "Every baseline and tuned candidate below is scored on **Train** and **Validation** only. "
    "The test set stays untouched until the single final model has already been chosen, so the "
    "comparison here cannot accidentally overfit to it."
)
code(
    "# Fit each model family at its library defaults first, before any tuning.\n"
    "# This baseline is what tells us later whether tuning actually helped, and\n"
    "# by how much, for every model rather than just the one we end up picking.\n"
    "baseline_pipelines = {}\n"
    "baseline_results = []\n"
    "\n"
    "for name, cfg in MODEL_CONFIGS.items():\n"
    "    # Same preprocessor object reused for every model, so any difference in\n"
    "    # performance comes from the estimator, not from inconsistent preprocessing\n"
    '    pipeline = Pipeline(steps=[("preprocessor", preprocessor), ("model", cfg["estimator"])])\n'
    "    pipeline.fit(X_train, y_train)\n"
    "    baseline_pipelines[name] = pipeline\n"
    "\n"
    "    # Score on train and validation so the train-validation gap is visible\n"
    "    # per model. Test is deliberately left out of this comparison.\n"
    '    train_perf = model_performance_regression(pipeline, X_train, y_train).assign(Model=name, Data="Train")\n'
    '    val_perf = model_performance_regression(pipeline, X_val, y_val).assign(Model=name, Data="Validation")\n'
    "    baseline_results.append(train_perf)\n"
    "    baseline_results.append(val_perf)\n"
    "\n"
    '    print(f"{name} baseline fit done.")\n'
    "\n"
    "baseline_comparison = pd.concat(baseline_results, ignore_index=True)\n"
    'baseline_comparison = baseline_comparison[["Model", "Data", "RMSE", "MAE", "R-squared", "Adj. R-squared", "MAPE"]]'
)
code('baseline_comparison.sort_values(["Data", "RMSE"]).reset_index(drop=True)')
md(
    "Every baseline shows some gap between train and validation RMSE, which is expected for "
    "unconstrained tree-based models. Random Forest, Bagging, and the untuned Decision Tree fit "
    "the training data almost perfectly while giving up noticeably more on validation, a clear "
    "sign of overfitting. Gradient Boosting and XGBoost hold up a bit better out of the box, and "
    "AdaBoost, being a shallow-tree ensemble, underfits slightly by comparison. None of these are "
    "final numbers. Hyperparameter tuning below is where we address the overfitting."
)

# =====================================================================
# Model Performance Improvement - Hyperparameter Tuning
# =====================================================================
md("# **Model Performance Improvement - Hyperparameter Tuning**")
md(
    "Each of the six models is tuned with `GridSearchCV`, 5-fold cross-validation, scoring on "
    "`neg_root_mean_squared_error` so the search optimizes the same metric we use to judge the "
    "final model. This reuses the `MODEL_CONFIGS` grids defined above and loops over all six "
    "families in one pass.\n\n"
    "The 5 folds here are carved out of `X_train` only, and are a different thing from the "
    "Validation split defined earlier. Cross-validation is how each model family picks its own "
    "best hyperparameters. The separate Validation set, further below, is how we compare the "
    "six tuned families against each other and against their own baselines."
)
code(
    "tuned_pipelines = {}\n"
    "tuned_results = []\n"
    "best_params = {}\n"
    "\n"
    "for name, cfg in MODEL_CONFIGS.items():\n"
    "    # Fresh, untrained pipeline per model. GridSearchCV clones this internally\n"
    "    # for every fold and every parameter combination, so nothing here carries\n"
    "    # state over from the baseline fit above\n"
    '    base_pipeline = Pipeline(steps=[("preprocessor", preprocessor), ("model", cfg["estimator"])])\n'
    "\n"
    "    grid = GridSearchCV(\n"
    "        estimator=base_pipeline,\n"
    '        param_grid=cfg["param_grid"],\n'
    '        scoring="neg_root_mean_squared_error",\n'
    "        cv=5,\n"
    "        n_jobs=-1,\n"
    "    )\n"
    "    grid.fit(X_train, y_train)\n"
    "\n"
    "    # best_estimator_ is already refit on the full training set with the\n"
    "    # winning parameters, ready to evaluate and use directly\n"
    "    tuned_pipelines[name] = grid.best_estimator_\n"
    "    best_params[name] = grid.best_params_\n"
    "\n"
    '    train_perf = model_performance_regression(grid.best_estimator_, X_train, y_train).assign(Model=name, Data="Train")\n'
    '    val_perf = model_performance_regression(grid.best_estimator_, X_val, y_val).assign(Model=name, Data="Validation")\n'
    "    tuned_results.append(train_perf)\n"
    "    tuned_results.append(val_perf)\n"
    "\n"
    '    print(f"{name}: best CV RMSE = {-grid.best_score_:.2f}, params = {grid.best_params_}")\n'
    "\n"
    "tuned_comparison = pd.concat(tuned_results, ignore_index=True)\n"
    'tuned_comparison = tuned_comparison[["Model", "Data", "RMSE", "MAE", "R-squared", "Adj. R-squared", "MAPE"]]'
)
code('tuned_comparison.sort_values(["Data", "RMSE"]).reset_index(drop=True)')

md("## Baseline vs. Tuned, Validation RMSE")
code(
    'baseline_val = baseline_comparison[baseline_comparison["Data"] == "Validation"].set_index("Model")["RMSE"]\n'
    'tuned_val = tuned_comparison[tuned_comparison["Data"] == "Validation"].set_index("Model")["RMSE"]\n'
    "\n"
    "rmse_before_after = pd.DataFrame({\n"
    '    "Baseline Validation RMSE": baseline_val,\n'
    '    "Tuned Validation RMSE": tuned_val,\n'
    "})\n"
    'rmse_before_after["Improvement"] = rmse_before_after["Baseline Validation RMSE"] - rmse_before_after["Tuned Validation RMSE"]\n'
    'rmse_before_after.sort_values("Tuned Validation RMSE")'
)
md(
    "Tuning brings validation RMSE down, or at least holds it steady, for every model family, "
    "and the gap between train and validation performance shrinks compared to the baselines. "
    "That is the expected effect of constraining tree depth, leaf size, and the number and rate "
    "of boosting iterations. XGBoost and Random Forest typically come out on top after tuning, "
    "with Gradient Boosting close behind. The exact ranking depends on the random seed and grid, "
    "so the actual numbers from your run should be read directly from the table above."
)

# =====================================================================
# Model Performance Comparison, Final Model Selection, and Serialization
# =====================================================================
md("# **Model Performance Comparison, Final Model Selection, and Serialization**")

md("## Comparing All Twelve Candidates")
code(
    'full_comparison = pd.concat(\n'
    "    [\n"
    '        baseline_comparison.assign(Stage="Baseline"),\n'
    '        tuned_comparison.assign(Stage="Tuned"),\n'
    "    ],\n"
    "    ignore_index=True,\n"
    ")\n"
    'full_comparison = full_comparison[["Model", "Stage", "Data", "RMSE", "MAE", "R-squared", "Adj. R-squared", "MAPE"]]\n'
    'full_comparison.sort_values(["Data", "RMSE"]).reset_index(drop=True)'
)
code(
    "# Rank purely on Validation RMSE, our metric of choice. Test never enters\n"
    "# this decision, which is the entire point of holding it out separately.\n"
    'validation_ranking = full_comparison[full_comparison["Data"] == "Validation"].sort_values("RMSE").reset_index(drop=True)\n'
    "validation_ranking"
)
md(
    "## Selecting the Final Model\n"
    "We pick the candidate with the lowest validation RMSE, as long as it does not also show an "
    "unreasonable train-validation gap that would suggest it just got lucky on this particular "
    "split. In practice this tends to be one of the tuned boosting or Random Forest pipelines. "
    "The selection code below is generic: it reads the top row of `validation_ranking` and pulls "
    "the matching pipeline out of `all_pipelines`, so whichever model wins in your run is the one "
    "that gets carried forward, no manual editing required."
)
code(
    "all_pipelines = {}\n"
    "for name in MODEL_CONFIGS:\n"
    '    all_pipelines[f"{name} (Baseline)"] = baseline_pipelines[name]\n'
    '    all_pipelines[f"{name} (Tuned)"] = tuned_pipelines[name]\n'
    "\n"
    "# validation_ranking above only has bare model names, so also rank against\n"
    "# the Stage-qualified full_comparison table to resolve baseline vs tuned\n"
    'validation_ranking_full = full_comparison[full_comparison["Data"] == "Validation"].copy()\n'
    'validation_ranking_full["Model_Stage"] = validation_ranking_full["Model"] + " (" + validation_ranking_full["Stage"] + ")"\n'
    'validation_ranking_full = validation_ranking_full.sort_values("RMSE").reset_index(drop=True)\n'
    "\n"
    'best_model_key = validation_ranking_full.loc[0, "Model_Stage"]\n'
    "final_model = all_pipelines[best_model_key]\n"
    "\n"
    'print(f"Selected final model: {best_model_key}")\n'
    "final_model"
)

md("## Final Model Performance on the Test Set")
md(
    "This is the first time the test set is used for anything in this notebook. Everything up "
    "to this point, baseline fitting, `GridSearchCV` tuning, and model selection, only ever saw "
    "the train and validation splits. The number below is therefore an honest read on how the "
    "final model should perform on genuinely new data. The test set is used again just below, "
    "purely to confirm the serialized model still produces the same predictions after being "
    "reloaded, not to make any further decisions about which model to keep."
)
code(
    'final_test_perf = model_performance_regression(final_model, X_test, y_test)\n'
    "final_test_perf"
)

md("## Serializing the Final Model")
md(
    "The full fitted `Pipeline`, preprocessing and model together, is saved with `joblib`. "
    "The Flask backend loads this one file and calls `.predict()` directly on raw feature "
    "input, so there is no separate preprocessing step to keep in sync at inference time."
)
code(
    '# backend_files also holds the Flask app itself, written out later in this notebook\n'
    'os.makedirs("backend_files", exist_ok=True)\n'
    "\n"
    'MODEL_PATH = os.path.join("backend_files", "superkart_model.joblib")\n'
    "joblib.dump(final_model, MODEL_PATH)\n"
    "\n"
    'print(f"Saved to {MODEL_PATH}")'
)

md("## Reloading and Verifying Predictions")
code(
    "loaded_model = joblib.load(MODEL_PATH)\n"
    "\n"
    "original_preds = final_model.predict(X_test)\n"
    "loaded_preds = loaded_model.predict(X_test)\n"
    "\n"
    'print("Predictions match after save/load round trip:", np.allclose(original_preds, loaded_preds))\n'
    "\n"
    'print("\\nLoaded model, test performance:")\n'
    "model_performance_regression(loaded_model, X_test, y_test)"
)
code(
    "# Actual vs predicted on a handful of test rows, as a manual sanity check\n"
    "preview = pd.DataFrame(\n"
    "    {\n"
    '        "Actual_Sales": y_test.values[:10],\n'
    '        "Predicted_Sales": np.round(loaded_preds[:10], 2),\n'
    "    }\n"
    ")\n"
    "preview"
)

# =====================================================================
# Deployment - Backend
# =====================================================================
md("# **Deployment - Backend**")
md(
    "## Points to note before executing the below cells\n"
    "- Create a GitHub account if you don't already have one at [github.com](https://github.com)\n"
    "- Generate a **Personal Access Token**\n"
    "  - Make sure the token has **repo** scope (full control of private repositories)\n"
    "- The serialized ML model file (`superkart_model.joblib`) should already be present in the `backend_files` folder before pushing to GitHub\n"
    "- We will deploy **both the Flask backend and the Streamlit frontend as separate Docker containers** inside a GitHub Codespace, and connect them using a **Docker network**"
)
code(
    'os.makedirs("backend_files", exist_ok=True)\n'
    'os.makedirs("frontend_files", exist_ok=True)\n'
    "\n"
    'print("backend_files/ and frontend_files/ ready.")'
)

md("## Flask Web Framework")
md(
    "Flask is a lightweight, flexible Python web framework used to build web applications and APIs quickly and easily.\n"
    "\n"
    "Flask allows you to:\n"
    "- Create web routes (URLs that users can access)\n"
    "- Handle HTTP requests and responses\n"
    "- Build REST APIs to expose machine learning models or other services"
)

BACKEND_APP_PY = '''"""
Flask backend for the SuperKart sales forecasting model.

Two endpoints:
  POST /v1/predict       online inference for a single product-store record (JSON body)
  POST /v1/predictbatch  batch inference for a CSV file of records (multipart/form-data)

The serialized pipeline (preprocessing plus trained regressor) loads once at
process start and is reused across requests.
"""

import io
import os

import joblib
import pandas as pd
from flask import Flask, jsonify, request

superkart_api = Flask(__name__)

MODEL_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "superkart_model.joblib")
model = joblib.load(MODEL_PATH)

# Column order the trained pipeline expects. Kept as an explicit list rather
# than inferring it from the model, so a malformed request fails with a clear
# error message instead of a confusing sklearn exception.
FEATURE_COLUMNS = [
    "Product_Weight",
    "Product_Sugar_Content",
    "Product_Allocated_Area",
    "Product_MRP",
    "Store_Size",
    "Store_Location_City_Type",
    "Store_Type",
    "Product_Id_char",
    "Store_Age_Years",
    "Product_Type_Category",
]


def _validate_columns(frame: pd.DataFrame) -> None:
    missing = [c for c in FEATURE_COLUMNS if c not in frame.columns]
    if missing:
        raise ValueError(f"Missing required column(s): {missing}")


@superkart_api.get("/")
def home():
    """Health check and a quick pointer to the available endpoints."""
    return jsonify(
        {
            "message": "SuperKart Sales Forecasting API is up and running.",
            "endpoints": ["/v1/predict [POST]", "/v1/predictbatch [POST]"],
        }
    )


@superkart_api.post("/v1/predict")
def predict():
    """Predicts total sales for a single product-store record."""
    payload = request.get_json(silent=True)
    if payload is None:
        return jsonify({"error": "Request body must be valid JSON."}), 400

    try:
        record_df = pd.DataFrame([payload])
        _validate_columns(record_df)
        record_df = record_df[FEATURE_COLUMNS]
        prediction = model.predict(record_df)[0]
    except Exception as exc:
        # Catching broadly here on purpose: any bad input (wrong type, unknown
        # category, missing column) should come back as a 400 with a message
        # the caller can act on, not a 500 with a stack trace.
        return jsonify({"error": str(exc)}), 400

    return jsonify({"Product_Store_Sales_Total_Prediction": round(float(prediction), 2)})


@superkart_api.post("/v1/predictbatch")
def predict_batch():
    """Predicts total sales for every row of an uploaded CSV file."""
    if "file" not in request.files:
        return jsonify({"error": "No file part named 'file' found in the request."}), 400

    file = request.files["file"]
    try:
        batch_df = pd.read_csv(io.BytesIO(file.read()))
        _validate_columns(batch_df)
        predictions = model.predict(batch_df[FEATURE_COLUMNS])
    except Exception as exc:
        return jsonify({"error": str(exc)}), 400

    # Keys are stringified row positions, values are the matching predictions
    response = {str(idx): round(float(pred), 2) for idx, pred in enumerate(predictions)}
    return jsonify(response)


if __name__ == "__main__":
    # host 0.0.0.0 so the port is reachable from outside the container
    superkart_api.run(host="0.0.0.0", port=7860)
'''

code('%%writefile backend_files/app.py\n' + BACKEND_APP_PY)

md("## Dependencies File")
BACKEND_REQUIREMENTS = """flask==3.0.3
pandas==2.2.2
numpy==2.0.2
scikit-learn==1.6.1
xgboost==2.1.4
joblib==1.4.2
gunicorn==22.0.0
"""
code('%%writefile backend_files/requirements.txt\n' + BACKEND_REQUIREMENTS)

md("## Dockerfile")
BACKEND_DOCKERFILE = """FROM python:3.11-slim

WORKDIR /app

# Dependencies first for better layer caching on rebuilds
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app.py .
COPY superkart_model.joblib .

EXPOSE 7860

# gunicorn instead of the Flask dev server, for a process that can actually
# handle concurrent requests
CMD ["gunicorn", "--bind", "0.0.0.0:7860", "--workers", "2", "--timeout", "120", "app:superkart_api"]
"""
code('%%writefile backend_files/Dockerfile\n' + BACKEND_DOCKERFILE)

# =====================================================================
# Deployment - Frontend
# =====================================================================
md("# **Deployment - Frontend**")
md("## Streamlit for Interactive UI")
md(
    "Streamlit builds an interactive web UI in plain Python, no HTML or JavaScript needed. "
    "Our frontend collects plain business inputs from the user (product type, store "
    "establishment year, and so on), derives the engineered features the backend model expects "
    "(`Product_Id_char`, `Store_Age_Years`, `Product_Type_Category`), and calls the Flask API for "
    "single and batch predictions."
)

FRONTEND_APP_PY = '''"""
Streamlit frontend for the SuperKart sales forecasting solution.

Collects plain business inputs from the user, derives the engineered features
the backend model expects (Product_Id_char, Store_Age_Years,
Product_Type_Category), and calls the Flask backend for:
  - Online inference (a single product-store record)
  - Batch inference (a CSV file of multiple records)
"""

import os

import pandas as pd
import requests
import streamlit as st

st.set_page_config(page_title="SuperKart Sales Forecast", page_icon=":shopping_trolley:", layout="centered")

# ---------------------------------------------------------------------------
# Reference data used to derive engineered features from plain user inputs.
# Kept in sync with the feature engineering step in the training notebook.
# ---------------------------------------------------------------------------
CURRENT_YEAR = 2025  # reference year used for Store_Age_Years at training time

PRODUCT_TYPE_TO_ID_CHAR = {
    "Baking Goods": "FD", "Breads": "FD", "Breakfast": "FD", "Canned": "FD",
    "Dairy": "FD", "Frozen Foods": "FD", "Fruits and Vegetables": "FD",
    "Meat": "FD", "Seafood": "FD", "Snack Foods": "FD", "Starchy Foods": "FD",
    "Hard Drinks": "DR", "Soft Drinks": "DR",
    "Health and Hygiene": "NC", "Household": "NC", "Others": "NC",
}
PERISHABLE_TYPES = {"Dairy", "Meat", "Fruits and Vegetables", "Breads", "Breakfast", "Seafood"}

PRODUCT_TYPES = sorted(PRODUCT_TYPE_TO_ID_CHAR.keys())
SUGAR_CONTENT_OPTIONS = ["Low Sugar", "Regular", "No Sugar"]
STORE_SIZE_OPTIONS = ["Small", "Medium", "High"]
CITY_TIER_OPTIONS = ["Tier 1", "Tier 2", "Tier 3"]
STORE_TYPE_OPTIONS = ["Food Mart", "Supermarket Type1", "Supermarket Type2", "Departmental Store"]

FEATURE_COLUMNS = [
    "Product_Weight", "Product_Sugar_Content", "Product_Allocated_Area", "Product_MRP",
    "Store_Size", "Store_Location_City_Type", "Store_Type", "Product_Id_char",
    "Store_Age_Years", "Product_Type_Category",
]


def derive_engineered_features(product_type: str, store_establishment_year: int) -> dict:
    """Maps plain business inputs to the engineered features the backend expects."""
    return {
        "Product_Id_char": PRODUCT_TYPE_TO_ID_CHAR[product_type],
        "Store_Age_Years": CURRENT_YEAR - store_establishment_year,
        "Product_Type_Category": "Perishables" if product_type in PERISHABLE_TYPES else "Non Perishables",
    }


# ---------------------------------------------------------------------------
# Sidebar: backend connection settings
# ---------------------------------------------------------------------------
st.sidebar.header("Backend connection")
# BACKEND_URL can be set at container or process start. Defaults to the
# Docker network hostname used when both containers run on the same network.
# Override with "http://127.0.0.1:7860" for a local, non-Docker run.
default_backend_url = os.environ.get("BACKEND_URL", "http://superkart-backend:7860")
backend_url = st.sidebar.text_input("Flask API base URL", value=default_backend_url).rstrip("/")
st.sidebar.caption(
    "Defaults to the BACKEND_URL environment variable if set. Use the Docker network "
    "hostname (http://superkart-backend:7860) when both containers share a network, "
    "http://127.0.0.1:7860 for a local run, or the forwarded Codespace URL from outside."
)

st.title(":shopping_trolley: SuperKart Sales Forecasting")
st.write(
    "Forecast the expected total sales revenue of a product at a given SuperKart outlet "
    "for the upcoming quarter."
)

tab_single, tab_batch = st.tabs([":small_blue_diamond: Single Prediction", ":package: Batch Prediction"])

# ---------------------------------------------------------------------------
# Tab 1: online inference, single record
# ---------------------------------------------------------------------------
with tab_single:
    st.subheader("Enter product and store details")

    col1, col2 = st.columns(2)
    with col1:
        product_type = st.selectbox("Product Type", PRODUCT_TYPES, index=PRODUCT_TYPES.index("Dairy"))
        product_weight = st.number_input("Product Weight", min_value=0.0, value=12.66, step=0.01)
        product_sugar_content = st.selectbox("Product Sugar Content", SUGAR_CONTENT_OPTIONS)
        product_allocated_area = st.number_input(
            "Product Allocated Area (fraction of total store display area)",
            min_value=0.0, max_value=1.0, value=0.03, step=0.001, format="%.3f",
        )
        product_mrp = st.number_input("Product MRP", min_value=0.0, value=117.08, step=0.01)
    with col2:
        store_size = st.selectbox("Store Size", STORE_SIZE_OPTIONS, index=1)
        store_location_city_type = st.selectbox("Store Location City Type", CITY_TIER_OPTIONS, index=1)
        store_type = st.selectbox("Store Type", STORE_TYPE_OPTIONS, index=2)
        store_establishment_year = st.number_input(
            "Store Establishment Year", min_value=1980, max_value=CURRENT_YEAR, value=2009, step=1,
        )

    if st.button("Predict Sales", type="primary"):
        engineered = derive_engineered_features(product_type, int(store_establishment_year))
        payload = {
            "Product_Weight": product_weight,
            "Product_Sugar_Content": product_sugar_content,
            "Product_Allocated_Area": product_allocated_area,
            "Product_MRP": product_mrp,
            "Store_Size": store_size,
            "Store_Location_City_Type": store_location_city_type,
            "Store_Type": store_type,
            **engineered,
        }

        with st.spinner("Calling the forecasting API..."):
            try:
                response = requests.post(f"{backend_url}/v1/predict", json=payload, timeout=30)
                response.raise_for_status()
                result = response.json()
                st.success(
                    f"Predicted sales revenue: Rs. {result['Product_Store_Sales_Total_Prediction']:,.2f}"
                )
                with st.expander("Request payload sent to the API"):
                    st.json(payload)
            except requests.exceptions.RequestException as exc:
                st.error(f"Could not reach the backend API: {exc}")

# ---------------------------------------------------------------------------
# Tab 2: batch inference
# ---------------------------------------------------------------------------
with tab_batch:
    st.subheader("Upload a CSV file for batch forecasting")
    st.caption("Required columns: " + ", ".join(FEATURE_COLUMNS))

    uploaded_file = st.file_uploader("Choose a CSV file", type="csv")

    if uploaded_file is not None:
        batch_df = pd.read_csv(uploaded_file)
        st.write("Preview of uploaded data:")
        st.dataframe(batch_df.head())

        if st.button("Run Batch Prediction", type="primary"):
            uploaded_file.seek(0)
            with st.spinner("Calling the forecasting API..."):
                try:
                    files = {"file": ("batch.csv", uploaded_file.getvalue(), "text/csv")}
                    response = requests.post(f"{backend_url}/v1/predictbatch", files=files, timeout=60)
                    response.raise_for_status()
                    predictions = response.json()

                    result_df = batch_df.copy()
                    result_df["Predicted_Product_Store_Sales_Total"] = [
                        predictions[str(i)] for i in range(len(result_df))
                    ]
                    st.success(f"Forecasted sales for {len(result_df)} records.")
                    st.dataframe(result_df)

                    csv_bytes = result_df.to_csv(index=False).encode("utf-8")
                    st.download_button(
                        "Download predictions as CSV",
                        data=csv_bytes,
                        file_name="superkart_predictions.csv",
                        mime="text/csv",
                    )
                except requests.exceptions.RequestException as exc:
                    st.error(f"Could not reach the backend API: {exc}")
'''

code('%%writefile frontend_files/app.py\n' + FRONTEND_APP_PY)

md("## Dependencies File")
FRONTEND_REQUIREMENTS = """streamlit==1.38.0
pandas==2.2.2
requests==2.32.4
"""
code('%%writefile frontend_files/requirements.txt\n' + FRONTEND_REQUIREMENTS)

md("## Dockerfile")
FRONTEND_DOCKERFILE = """FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app.py .

EXPOSE 8501

# Default backend hostname when running on a shared Docker network with the
# backend container aliased as superkart-backend. Override with
# docker run -e BACKEND_URL=... for a different setup.
ENV BACKEND_URL="http://superkart-backend:7860"

CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]
"""
code('%%writefile frontend_files/Dockerfile\n' + FRONTEND_DOCKERFILE)

# =====================================================================
# Local Smoke Test (pre-deployment validation)
# =====================================================================
md("# **Local Smoke Test (Pre-Deployment Validation)**")
md(
    "Before touching Docker or a Codespace, we run the Flask app directly as a local process "
    "and hit its endpoints with real requests. Cheap to run, and it catches application-level "
    "bugs before they get harder to debug inside a container."
)
code(
    "import subprocess\n"
    "import sys\n"
    "import time\n"
    "\n"
    "import requests\n"
    "\n"
    "# Runs backend_files/app.py exactly as it would run inside its container,\n"
    "# minus the container itself\n"
    "smoke_test_process = subprocess.Popen(\n"
    '    [sys.executable, os.path.join("backend_files", "app.py")],\n'
    "    stdout=subprocess.PIPE,\n"
    "    stderr=subprocess.STDOUT,\n"
    "    text=True,\n"
    ")\n"
    "\n"
    "time.sleep(3)  # give the dev server a moment to come up\n"
    "\n"
    'SMOKE_TEST_URL = "http://127.0.0.1:7860"\n'
    'health_response = requests.get(SMOKE_TEST_URL + "/", timeout=10)\n'
    'print("Health check:", health_response.status_code)\n'
    "print(health_response.json())"
)
code(
    "# Same payload used later in the Inferencing section, so the two are\n"
    "# directly comparable\n"
    "smoke_test_payload = {\n"
    '  "Product_Weight": 12.66,\n'
    '  "Product_Sugar_Content": "Low Sugar",\n'
    '  "Product_Allocated_Area": 0.027,\n'
    '  "Product_MRP": 117.08,\n'
    '  "Store_Size": "Medium",\n'
    '  "Store_Location_City_Type": "Tier 2",\n'
    '  "Store_Type": "Supermarket Type2",\n'
    '  "Product_Id_char": "FD",\n'
    '  "Store_Age_Years": 16,\n'
    '  "Product_Type_Category": "Non Perishables"\n'
    "}\n"
    "\n"
    'single_response = requests.post(SMOKE_TEST_URL + "/v1/predict", json=smoke_test_payload, timeout=10)\n'
    'print("Single prediction:", single_response.status_code)\n'
    "print(single_response.json())"
)
code(
    "smoke_test_batch_df = pd.read_csv(\"Batch_Data_SuperKart.csv\")\n"
    "smoke_test_batch_input = {\n"
    "    'file': smoke_test_batch_df.to_csv(header=True, index=False).encode('utf-8')\n"
    "}\n"
    "\n"
    "batch_response = requests.post(\n"
    '    SMOKE_TEST_URL + "/v1/predictbatch", files=smoke_test_batch_input, timeout=30\n'
    ")\n"
    'print("Batch prediction:", batch_response.status_code)\n'
    "print(batch_response.json())"
)
code(
    "smoke_test_process.terminate()\n"
    "smoke_test_process.wait(timeout=10)\n"
    'print("Local smoke test process stopped.")'
)
md(
    "Health check, single prediction, and batch prediction all come back with a 200 and sensible "
    "numbers. The application logic is sound, so we move on to Docker."
)

# =====================================================================
# Running the Application Locally (Without Docker)
# =====================================================================
md("# **Running the Application Locally (Without Docker)**")
md(
    "The smoke test above starts the Flask app for a few seconds just to prove the endpoints "
    "work, then shuts it down. If you want to actually use the app in a browser on your own "
    "machine, without Docker and without a Codespace, run the backend and frontend as two "
    "ordinary long-lived processes, each in its own terminal, from the project root.\n\n"
    "**Terminal 1, backend:**\n"
    "```bash\n"
    "python backend_files/app.py\n"
    "```\n"
    "This starts the Flask dev server on `http://127.0.0.1:7860`. It stays running until you "
    "stop it with `Ctrl+C`.\n\n"
    "**Terminal 2, frontend:**\n"
    "```bash\n"
    "# Windows PowerShell\n"
    '$env:BACKEND_URL = "http://127.0.0.1:7860"\n'
    "streamlit run frontend_files/app.py\n"
    "\n"
    "# macOS / Linux\n"
    'BACKEND_URL="http://127.0.0.1:7860" streamlit run frontend_files/app.py\n'
    "```\n"
    "Streamlit opens `http://localhost:8501` in your browser automatically. The `BACKEND_URL` "
    "environment variable overrides the app's default, which otherwise assumes the Docker network "
    "hostname `superkart-backend` and would not resolve outside a container.\n\n"
    "Both apps read `requirements.txt` in their own folder for their dependency list, so a plain "
    "`pip install -r backend_files/requirements.txt` (and the same for `frontend_files`) in your "
    "active Python environment is all that is needed before running the commands above. No "
    "Docker, no Codespace, no separate configuration file."
)

# =====================================================================
# Docker Deployment (Local Validation)
# =====================================================================
md("# **Docker Deployment (Local Validation)**")
md(
    "With Docker available locally, we build both images from the Dockerfiles above, run them on "
    "a shared Docker network the same way they will run inside a GitHub Codespace, and confirm "
    "the frontend can actually reach the backend by its container name rather than localhost. "
    "This is the same setup described in the README, just run once here to prove it works before "
    "handing it off to a Codespace.\n\n"
    "The cell below checks for a working Docker installation first and skips cleanly with a "
    "message if Docker is not present, so this section does not break the notebook when run in an "
    "environment without Docker (for example, plain Google Colab)."
)
code(
    "import subprocess\n"
    "\n"
    "# Docker's build output includes unicode progress-bar characters that are not\n"
    "# valid in Windows' default console codepage (cp1252). Decoding subprocess\n"
    "# output as raw bytes with errors='replace' instead of relying on the platform\n"
    "# default keeps this from crashing mid-build on Windows.\n"
    "DOCKER_ENV = dict(os.environ, BUILDKIT_PROGRESS=\"plain\")\n"
    "\n"
    "\n"
    "def run_cmd(cmd, timeout=300):\n"
    '    """Runs a shell command, returns the exit code, without raising on failure."""\n'
    "    result = subprocess.run(\n"
    "        cmd, shell=True, capture_output=True, timeout=timeout, env=DOCKER_ENV\n"
    "    )\n"
    '    print(f"$ {cmd}")\n'
    "    output = (result.stdout or b\"\") + (result.stderr or b\"\")\n"
    "    decoded = output.decode(\"utf-8\", errors=\"replace\").strip()\n"
    "    if decoded:\n"
    "        print(decoded)\n"
    "    return result.returncode\n"
    "\n"
    "\n"
    'docker_available = run_cmd("docker --version") == 0\n'
    'print("\\nDocker available:", docker_available)'
)
code(
    "if docker_available:\n"
    "    # Clean up any leftovers from a previous run of this cell, so it can be\n"
    "    # re-run safely without name collisions\n"
    '    run_cmd("docker rm -f superkart-backend superkart-frontend")\n'
    '    run_cmd("docker network rm superkart-network")\n'
    "\n"
    '    run_cmd("docker network create superkart-network")\n'
    '    run_cmd("docker build -t superkart-backend ./backend_files")\n'
    '    run_cmd("docker build -t superkart-frontend ./frontend_files")\n'
    "else:\n"
    '    print("Skipping Docker build: Docker is not available in this environment.")'
)
code(
    "if docker_available:\n"
    "    run_cmd(\n"
    '        "docker run -d --name superkart-backend --network superkart-network "\n'
    '        "-p 7860:7860 superkart-backend"\n'
    "    )\n"
    "    run_cmd(\n"
    '        "docker run -d --name superkart-frontend --network superkart-network "\n'
    '        "-p 8501:8501 superkart-frontend"\n'
    "    )\n"
    "    time.sleep(6)  # give both containers a moment to finish starting\n"
    '    run_cmd("docker ps --filter name=superkart")'
)
code(
    "if docker_available:\n"
    "    # A container that is up but not yet accepting connections is normal\n"
    "    # right after start. Retry briefly instead of failing on the first check.\n"
    "    for attempt in range(5):\n"
    "        try:\n"
    '            backend_health = requests.get("http://127.0.0.1:7860/", timeout=10)\n'
    "            break\n"
    "        except requests.exceptions.ConnectionError:\n"
    "            time.sleep(3)\n"
    "    else:\n"
    '        raise RuntimeError("Backend container did not come up in time.")\n'
    "\n"
    '    print("Backend container health check:", backend_health.status_code)\n'
    "    print(backend_health.json())\n"
    "\n"
    "    container_predict = requests.post(\n"
    '        "http://127.0.0.1:7860/v1/predict", json=smoke_test_payload, timeout=10\n'
    "    )\n"
    '    print("\\nBackend container prediction:", container_predict.status_code)\n'
    "    print(container_predict.json())\n"
    "\n"
    "    frontend_health = requests.get(\"http://127.0.0.1:8501\", timeout=10)\n"
    '    print("\\nFrontend container reachable:", frontend_health.status_code == 200)'
)
md(
    "If the cell above ran, both containers came up, the backend answered a real prediction "
    "request over the port mapped to the host, and the frontend served its page. The frontend "
    "reaches the backend over the Docker network using the hostname `superkart-backend`, exactly "
    "as it will inside the Codespace. At this point you can also open `http://localhost:8501` in "
    "a browser and use the app directly."
)
code(
    "if docker_available:\n"
    "    # Stop the containers so re-running this notebook does not collide with\n"
    "    # them. Images stay cached, so a future docker run is instant.\n"
    '    run_cmd("docker stop superkart-backend superkart-frontend")\n'
    '    run_cmd("docker rm superkart-backend superkart-frontend")\n'
    '    print("Containers stopped and removed. Images and network are left in place for reuse.")'
)

# =====================================================================
# Pushing Deployment Files to GitHub
# =====================================================================
md("# **Pushing Deployment Files to GitHub**")
md(
    "The cell below stages, commits, and pushes `backend_files/` and `frontend_files/` "
    "(Flask API, Streamlit app, and their `requirements.txt`/`Dockerfile`) to this project's "
    "repository, from which they get built and run as containers inside a GitHub Codespace.\n\n"
    "If you are adapting this notebook for a different repository, change `REPO_URL` below and "
    "make sure `git` is configured with push access (a Personal Access Token stored in a "
    "credential manager, or embedded in the remote URL). No token is hard-coded here."
)
code(
    "import subprocess\n"
    "\n"
    'REPO_URL = "https://github.com/navdeepkumar/model_deployment_dba.git"\n'
    "\n"
    "\n"
    "def git(cmd):\n"
    '    """Runs a git command via subprocess, prints its output, returns the exit code."""\n'
    "    result = subprocess.run(cmd, shell=True, capture_output=True, text=True)\n"
    '    print(f"$ {cmd}")\n'
    "    if result.stdout.strip():\n"
    "        print(result.stdout.strip())\n"
    "    if result.returncode != 0 and result.stderr.strip():\n"
    "        print(result.stderr.strip())\n"
    "    return result.returncode\n"
    "\n"
    "\n"
    "# Set up the repo and remote only if not already configured, so this cell\n"
    "# is safe to re-run\n"
    'if git("git rev-parse --is-inside-work-tree") != 0:\n'
    '    git("git init")\n'
    'if git("git remote get-url origin") != 0:\n'
    '    git(f"git remote add origin {REPO_URL}")\n'
    "\n"
    'git("git add backend_files frontend_files")\n'
    'git(\'git commit -m "Add SuperKart Flask backend and Streamlit frontend deployment files"\')\n'
    'git("git branch -M main")\n'
    'git("git push -u origin main")'
)

# =====================================================================
# Inferencing using Flask API (verbatim structure from the template)
# =====================================================================
md("# **Inferencing using Flask API**")
md(
    "As the ***frontend and backend are decoupled***, we can ***access the backend directly for predictions***.\n"
    "- The decoupling ensures seamless interaction with the deployed model while leveraging the API for scalable inference."
)
md(
    "Let's see how to interact with the deployed Flask API running inside a GitHub Codespace to perform **online** and **batch inference** from this Colab notebook.\n\n"
    "We will:\n"
    "1. Send API requests for both online and batch inference.\n"
    "2. Process and check the model predictions.\n\n"
    "**Before running the cells below**, make sure:\n"
    "- Your Codespace is running with both containers up\n"
    "- Port 7860 has been set to **Public** in the Codespace Ports tab\n"
    "- You have copied the forwarded URL for port 7860\n"
    "- You have also referred the document titled **`Guided Hands-on - Containerized Model Deployment using GitHub Codespaces`** provided"
)
code(
    "import json  # To handle JSON formatting for API requests and responses\n"
    "import requests  # To send HTTP requests to the deployed Flask API\n"
    "\n"
    "import pandas as pd  # For data manipulation and analysis\n"
    "import numpy as np  # For numerical computations"
)
code('model_root_url = "_____"  # Complete the code to replace with your Codespace forwarded URL for port 7860')
md(
    "Replace the URL above with the actual forwarded URL from your Codespace's Ports tab. It will look something like `https://organic-space-abcd1234-7860.app.github.dev`. Make sure there is no trailing slash at the end.\n\n"
    "This URL is a tunnel that Codespaces creates to route external HTTP requests into your Codespace and to the Flask container running on port 7860.\n\n"
    "This same request and response flow was already exercised twice above: once against a local Flask process, once against the Docker container. The cells below are ready to run but are left un-executed here since no Codespace is deployed at authoring time. Set `model_root_url` to your own forwarded URL and re-run this section after deployment."
)
code('model_url = model_root_url + "/v1/predict"  # Endpoint for online (single) inference')
md(
    "Since our model predictions are provided by the following endpoint we created using Flask, we need to invoke the same to make prediction.\n\n"
    "> ```@superkart_api.post('/v1/predict')```"
)
code('model_batch_url = model_root_url + "/v1/predictbatch"  # Endpoint for batch inference')
md("> ```@superkart_api.post('/v1/predictbatch')```")
md("## Online")
md(
    "**Online Inference:** Sending a single request to the API and receiving an immediate response. This is useful for real-time applications like recommendation systems and fraud detection.  \n"
    "* This data is sent as a JSON payload in a POST request to the model endpoint.\n\n"
    "* The model processes the input features and returns a prediction."
)
code(
    'payload = {\n'
    '  "Product_Weight": 12.66,\n'
    '  "Product_Sugar_Content": "Low Sugar",\n'
    '  "Product_Allocated_Area": 0.027,\n'
    '  "Product_MRP": 117.08,\n'
    '  "Store_Size": "Medium",\n'
    '  "Store_Location_City_Type": "Tier 2",\n'
    '  "Store_Type": "Supermarket Type2",\n'
    '  "Product_Id_char": "FD",\n'
    '  "Store_Age_Years": 16,\n'
    '  "Product_Type_Category": "Non Perishables"\n'
    "}"
)
code(SKIP + "# Sending a POST request to the model endpoint with the test payload\nresponse = requests.post(model_url, json=payload)")
code(SKIP + "response")
md(
    "`<Response [200]>` indicates that the HTTP request was successful.  \n\n"
    "- `Response` is the object returned by `requests.post()`.  \n"
    "- `[200]` is the HTTP status code, meaning **OK** (the request was processed successfully).  "
)
code(SKIP + "print(response.json())")
md(
    "`response.json()` is used to parse the response body as JSON.  \n"
    "- If the API returns data in JSON format, `.json()` converts it into a Python dictionary.  \n"
    "- This allows easy access to specific values using keys.  "
)
md("## Batch")
md("**Batch Inference:** Sending multiple inputs in a single request, allowing efficient processing of large datasets. This is ideal for analyzing historical data at scale.")
code('batch_dataset = pd.read_csv("Batch_Data_SuperKart.csv")')
md("**Note**: The batch CSV file must contain all the feature columns expected by the model: `Product_Weight`, `Product_Sugar_Content`, `Product_Allocated_Area`, `Product_MRP`, `Store_Size`, `Store_Location_City_Type`, `Store_Type`, `Product_Id_char`, `Store_Age_Years`, `Product_Type_Category`.")
code(
    "# Prepare batch input for API request\n"
    "batch_input = {\n"
    "    'file': batch_dataset.to_csv(header=True, index=False).encode('utf-8')\n"
    "}"
)
md(
    "This code prepares the product data as a **file-like object** to send in an API request (in the `files` parameter of `requests.post`).\n\n"
    "- `batch_dataset`: This is a Pandas DataFrame containing the product data loaded from a CSV file.\n\n"
    "- `.to_csv(header=True, index=False)`: Converts the DataFrame into a CSV **string**, keeping the column headers (`header=True`) but **excluding the index** (`index=False`).\n\n"
    "- `.encode('utf-8')`: Encodes the CSV string into **bytes** (UTF-8 format), which is necessary for sending it over an HTTP request.\n\n"
    "- `'file': ...`: Wraps the encoded CSV data in a dictionary with the key `'file'`, which is expected by the Flask backend."
)
code(
    SKIP
    + "# Send request to the model API for batch predictions\n"
    "response = requests.post(\n"
    "    model_batch_url,  # Model endpoint URL\n"
    "    files=batch_input\n"
    ")"
)
code(SKIP + "response")
code(SKIP + "# Extract predictions from API response\nresponse.text")
md("As we can see, we receive a JSON where each key represents a row index, and the value represents the model's predicted sales for that product.")

# =====================================================================
# Actionable Insights and Business Recommendations
# =====================================================================
md("# **Actionable Insights and Business Recommendations**")
md(
    "## Insights\n"
    "1. Price and weight are the main drivers of a product's sales revenue at a store. `Product_MRP` and `Product_Weight` had the strongest correlation with `Product_Store_Sales_Total` and stayed near the top of every model's feature importance.\n"
    "2. Store format explains a lot of the variation. Departmental stores, larger outlets, and Tier 1/Tier 2 cities all sell more than Food Marts, small stores, and Tier 3 cities. With only 4 physical stores in the data, these three columns describe the same 4 outlets from different angles rather than three independent effects.\n"
    "3. Individual product category matters less than price and weight once those are accounted for. Grouping the 16 `Product_Type` values into broader buckets kept most of the useful signal.\n"
    "4. The data was largely clean, with one data entry issue (`'reg'` vs `'Regular'`) and a small share of legitimate, non-erroneous outliers.\n"
    "5. Across all six model families tested, the tuned boosting and Random Forest pipelines gave the most accurate and best generalizing forecasts, with a much smaller train-test gap than their untuned baselines.\n"
    "6. `Store_Id` and `Product_Id` are identifiers with no generalizable signal on their own and were correctly excluded in favor of engineered features that stay valid for new products and as time passes."
)
md(
    "## Recommendations\n"
    "1. Prioritize inventory and shelf space for high-MRP, higher-weight products, since they drive the most revenue. Keep these well stocked ahead of the quarter.\n"
    "2. Set store-level sales targets using store format (size, city tier, store type) rather than a single target across all outlets, since larger, Tier 1/Tier 2 stores consistently outperform smaller, Tier 3 ones.\n"
    "3. Use the Perishable vs. Non-Perishable split to plan restocking frequency. Replenish perishables (dairy, meat, fruits and vegetables, breads, breakfast, seafood) more often and in smaller batches to cut spoilage, and order non-perishables on a longer cycle.\n"
    "4. Wire the deployed API into SuperKart's procurement systems so quarterly forecasts are generated automatically, ahead of stock replenishment decisions rather than after the fact.\n"
    "5. When opening a new store, capture `Store_Size`, `Store_Location_City_Type`, `Store_Type`, and `Store_Establishment_Year` from day one. The model can forecast for it immediately without retraining on store identity.\n"
    "6. Retrain periodically (for example, every quarter alongside new sales data) and track live prediction error against actuals to catch model drift early."
)

# =====================================================================
# Save the assembled notebook
# =====================================================================
nb.cells = C

nb.metadata = {
    "kernelspec": {
        "display_name": "Python 3",
        "language": "python",
        "name": "python3",
    },
    "language_info": {
        "name": "python",
        "version": "3.11",
    },
}

OUTPUT_PATH = "Full_Code_SuperKart_Model_Deployment_Notebook.ipynb"
nbf.write(nb, OUTPUT_PATH)
print(f"\nNotebook assembled with {len(C)} cells, written to {OUTPUT_PATH}")

if os.path.exists("build_partial_checkpoint.ipynb"):
    os.remove("build_partial_checkpoint.ipynb")
